name: ServerUtils
main: com.SuperiorNetworks.Projects.ServerUtils.ServerUtils
version: 0.2
description: Server Utilities for your server!

commands:
  serverutilshelp:
    description: Shows general help about how to use this plugin.